name: advent_of_code_2021
description: Playground for Advent of Code 2021 submissions. 

publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  async: ^2.8.2
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1

